#!/usr/bin/env python3
"""Small dependency-light utilities for Open Knowledge Format bundles.

This is intentionally conservative. It checks the OKF v0.1 minimum plus a
practical quality bar for bundles generated by agents.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlparse
import json
import os
import re
import shutil
import sys
import tarfile
import zipfile

RESERVED_FILENAMES = {"index.md", "log.md"}
RECOMMENDED_FIELDS = ["title", "description", "tags", "timestamp"]
# Match Markdown links but not images (a leading `!` marks an image).
MD_LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
CITATION_HEADING_RE = re.compile(r"^#\s+Citations\s*$", re.IGNORECASE | re.MULTILINE)
YAML_BOUNDARY = "---"
SLUG_RE = re.compile(r"[^a-z0-9]+")
# Allow small clock skew before flagging a timestamp as future-dated.
FUTURE_TIMESTAMP_SKEW_SECONDS = 24 * 60 * 60


@dataclass
class Issue:
    severity: str  # error | warning | info
    path: str
    message: str


@dataclass
class Concept:
    path: Path
    rel: str
    frontmatter: dict[str, Any]
    body: str
    raw_frontmatter: str

    @property
    def concept_id(self) -> str:
        return self.rel[:-3] if self.rel.endswith(".md") else self.rel


@dataclass
class BundleReport:
    root: Path
    concepts: list[Concept] = field(default_factory=list)
    issues: list[Issue] = field(default_factory=list)
    indexes: list[str] = field(default_factory=list)
    logs: list[str] = field(default_factory=list)

    @property
    def errors(self) -> list[Issue]:
        return [i for i in self.issues if i.severity == "error"]

    @property
    def warnings(self) -> list[Issue]:
        return [i for i in self.issues if i.severity == "warning"]

    def to_dict(self) -> dict[str, Any]:
        return {
            "root": str(self.root),
            "concept_count": len(self.concepts),
            "index_count": len(self.indexes),
            "log_count": len(self.logs),
            "error_count": len(self.errors),
            "warning_count": len(self.warnings),
            "concepts": [
                {
                    "path": c.rel,
                    "concept_id": c.concept_id,
                    "type": c.frontmatter.get("type"),
                    "title": c.frontmatter.get("title"),
                    "description": c.frontmatter.get("description"),
                    "tags": c.frontmatter.get("tags"),
                }
                for c in self.concepts
            ],
            "issues": [i.__dict__ for i in self.issues],
        }


def _rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _starts_with_frontmatter(text: str) -> bool:
    lines = text.splitlines()
    return bool(lines and lines[0].lstrip("\ufeff").strip() == YAML_BOUNDARY)


def slugify_title(value: str, fallback: str = "concept") -> str:
    slug = SLUG_RE.sub("-", value.lower()).strip("-")
    return slug or fallback


def _strip_inline_comment(value: str) -> str:
    in_single = False
    in_double = False
    for idx, char in enumerate(value):
        if char == "'" and not in_double:
            in_single = not in_single
        elif char == '"' and not in_single:
            in_double = not in_double
        elif char == "#" and not in_single and not in_double:
            return value[:idx].rstrip()
    return value.strip()


def _parse_scalar(value: str) -> Any:
    value = _strip_inline_comment(value)
    if value == "":
        return ""
    if value in {"true", "True"}:
        return True
    if value in {"false", "False"}:
        return False
    if value in {"null", "Null", "~"}:
        return None
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        return value[1:-1]
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [_parse_scalar(part.strip()) for part in inner.split(",")]
    return value


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str, str, str | None]:
    """Parse basic YAML frontmatter.

    Uses PyYAML when available, then falls back to a minimal parser that supports
    common `key: value` and inline-list frontmatter.
    """
    if not text:
        return {}, text, "", "missing opening frontmatter boundary"

    lines = text.splitlines()
    if not lines or lines[0].lstrip("\ufeff").strip() != YAML_BOUNDARY:
        return {}, text, "", "missing opening frontmatter boundary"

    end_idx = None
    for i in range(1, len(lines)):
        if lines[i].strip() == YAML_BOUNDARY:
            end_idx = i
            break
    if end_idx is None:
        return {}, text, "", "missing closing frontmatter boundary"

    raw = "\n".join(lines[1:end_idx])
    body = "\n".join(lines[end_idx + 1 :]).lstrip("\n")

    try:
        import yaml  # type: ignore

        loaded = yaml.safe_load(raw) if raw.strip() else {}
        if loaded is None:
            loaded = {}
        if not isinstance(loaded, dict):
            return {}, body, raw, "frontmatter is not a mapping"
        return dict(loaded), body, raw, None
    except Exception:
        parsed: dict[str, Any] = {}
        current_key: str | None = None
        for line in raw.splitlines():
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            if line.startswith("  - ") and current_key:
                parsed.setdefault(current_key, [])
                if isinstance(parsed[current_key], list):
                    parsed[current_key].append(_parse_scalar(line[4:].strip()))
                continue
            if ":" not in line:
                return parsed, body, raw, f"unsupported frontmatter line: {line!r}"
            key, value = line.split(":", 1)
            key = key.strip()
            if not key:
                return parsed, body, raw, "empty frontmatter key"
            value = value.strip()
            current_key = key
            if value == "":
                parsed[key] = []
            else:
                parsed[key] = _parse_scalar(value)
        return parsed, body, raw, None


def scan_bundle(root: str | Path, strict: bool = False) -> BundleReport:
    root_path = Path(root).resolve()
    report = BundleReport(root=root_path)
    if not root_path.exists():
        report.issues.append(Issue("error", str(root_path), "Bundle path does not exist."))
        return report
    if not root_path.is_dir():
        report.issues.append(Issue("error", str(root_path), "Bundle path is not a directory."))
        return report

    markdown_files = sorted(root_path.rglob("*.md"))
    if not markdown_files:
        report.issues.append(Issue("warning", ".", "No Markdown files found."))

    for path in markdown_files:
        rel = _rel(path, root_path)
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError as exc:
            report.issues.append(Issue("error", rel, f"Markdown file is not valid UTF-8: {exc}"))
            continue
        if path.name == "index.md":
            report.indexes.append(rel)
            if _starts_with_frontmatter(text):
                report.issues.append(Issue("warning", rel, "index.md should not contain frontmatter."))
            continue
        if path.name == "log.md":
            report.logs.append(rel)
            if _starts_with_frontmatter(text):
                report.issues.append(Issue("warning", rel, "log.md should not contain frontmatter."))
            _check_log(path, rel, text, report)
            continue

        fm, body, raw, parse_error = parse_frontmatter(text)
        if parse_error:
            report.issues.append(Issue("error", rel, parse_error))
            continue
        if "type" not in fm or not str(fm.get("type", "")).strip():
            report.issues.append(Issue("error", rel, "Concept is missing required frontmatter field `type`."))
        else:
            if not isinstance(fm.get("type"), str):
                report.issues.append(Issue("warning", rel, "Frontmatter field `type` should be a short string."))

        for key in RECOMMENDED_FIELDS:
            if key not in fm or fm.get(key) in (None, "", []):
                report.issues.append(Issue("warning", rel, f"Recommended frontmatter field `{key}` is missing or empty."))

        if "description" in fm and len(str(fm.get("description", ""))) > 240:
            report.issues.append(Issue("warning", rel, "`description` is long; keep it to one sentence for index snippets."))

        if "tags" in fm and fm.get("tags") not in (None, "") and not isinstance(fm.get("tags"), list):
            report.issues.append(Issue("warning", rel, "`tags` should be a YAML list."))

        if "resource" in fm:
            if fm.get("resource") in (None, "", []):
                report.issues.append(Issue("warning", rel, "`resource` is empty; omit it when there is no canonical URI."))
            else:
                parsed = urlparse(str(fm["resource"]))
                if not parsed.scheme:
                    report.issues.append(Issue("warning", rel, "`resource` should be a URI with a scheme, or be omitted."))

        if "timestamp" in fm and fm.get("timestamp"):
            parsed_ts = _parse_iso8601(str(fm["timestamp"]))
            if parsed_ts is None:
                report.issues.append(Issue("warning", rel, "`timestamp` should be ISO 8601, preferably with timezone."))
            else:
                now = datetime.now(parsed_ts.tzinfo) if parsed_ts.tzinfo else datetime.now()
                if (parsed_ts - now).total_seconds() > FUTURE_TIMESTAMP_SKEW_SECONDS:
                    report.issues.append(Issue("warning", rel, "`timestamp` is in the future; check the concept's date."))

        if not body.strip():
            report.issues.append(Issue("warning", rel, "Concept body is empty."))
        elif len(body.strip()) < 120:
            report.issues.append(Issue("warning", rel, "Concept body is very short; check whether it is useful to an agent."))

        if _has_external_links(body) and not CITATION_HEADING_RE.search(body):
            report.issues.append(Issue("warning", rel, "External links found but no `# Citations` section."))

        report.concepts.append(Concept(path=path, rel=rel, frontmatter=fm, body=body, raw_frontmatter=raw))

    _check_indexes(report)
    _check_links(report)
    _check_duplicates(report)
    _check_orphans(report)

    if strict:
        for issue in report.issues:
            if issue.severity == "warning":
                issue.severity = "error"

    return report


def _parse_iso8601(value: str) -> datetime | None:
    candidate = value.strip().replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(candidate)
    except ValueError:
        return None


def _looks_like_iso8601(value: str) -> bool:
    return _parse_iso8601(value) is not None


def _has_external_links(body: str) -> bool:
    return bool(re.search(r"\]\(https?://", body))


def _check_log(path: Path, rel: str, text: str, report: BundleReport) -> None:
    for line in text.splitlines():
        if line.startswith("## "):
            heading = line[3:].strip()
            if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", heading):
                report.issues.append(Issue("warning", rel, f"Log date heading should be YYYY-MM-DD: {heading!r}."))


def _check_indexes(report: BundleReport) -> None:
    expected_dirs = _concept_tree_dirs(report)
    for directory in sorted(expected_dirs, key=lambda path: path.as_posix()):
        index_path = "index.md" if directory == Path(".") else f"{directory.as_posix()}/index.md"
        if index_path not in report.indexes:
            if directory == Path("."):
                message = "Root index.md is missing. It is optional in OKF but strongly recommended."
            else:
                message = "Directory participates in the concept tree but has no index.md for progressive disclosure."
            report.issues.append(Issue("warning", index_path, message))


def _concept_tree_dirs(report: BundleReport) -> set[Path]:
    dirs: set[Path] = {Path(".")}
    for concept in report.concepts:
        parts = Path(concept.rel).parent.parts
        current = Path(".")
        dirs.add(current)
        for part in parts:
            if part == ".":
                continue
            current = current / part
            dirs.add(current)
    return dirs


def _iter_internal_links(body: str) -> Iterable[str]:
    for _text, target in MD_LINK_RE.findall(body):
        target = target.strip()
        if not target or target.startswith("#"):
            continue
        parsed = urlparse(target)
        if parsed.scheme or target.startswith("mailto:"):
            continue
        clean = target.split("#", 1)[0].strip()
        if clean:
            yield clean


def _resolve_link(source_rel: str, target: str, root: Path) -> Path:
    if target.startswith("/"):
        return (root / target.lstrip("/")).resolve()
    return (root / Path(source_rel).parent / target).resolve()


def _check_links(report: BundleReport) -> None:
    valid_targets = {c.path.resolve() for c in report.concepts}
    valid_targets.update((report.root / idx).resolve() for idx in report.indexes)
    for concept in report.concepts:
        for target in _iter_internal_links(concept.body):
            target_path = _resolve_link(concept.rel, target, report.root)
            if target.endswith("/"):
                index_path = target_path / "index.md"
                if index_path.resolve() not in valid_targets:
                    report.issues.append(Issue("warning", concept.rel, f"Directory link has no target index.md: {target}"))
            elif target_path not in valid_targets:
                report.issues.append(Issue("warning", concept.rel, f"Broken internal link: {target}"))


def _check_duplicates(report: BundleReport) -> None:
    seen_titles: dict[str, str] = {}
    for concept in report.concepts:
        title = str(concept.frontmatter.get("title", "")).strip().lower()
        if not title:
            continue
        if title in seen_titles:
            report.issues.append(Issue("warning", concept.rel, f"Duplicate title also used by {seen_titles[title]}."))
        else:
            seen_titles[title] = concept.rel


def _check_orphans(report: BundleReport) -> None:
    incoming: dict[str, int] = {c.rel: 0 for c in report.concepts}
    rel_by_path = {c.path.resolve(): c.rel for c in report.concepts}

    # Count links from concept bodies.
    for concept in report.concepts:
        for target in _iter_internal_links(concept.body):
            target_path = _resolve_link(concept.rel, target, report.root)
            target_rel = rel_by_path.get(target_path)
            if target_rel:
                incoming[target_rel] += 1

    # Count links from index files as discoverability edges.
    for index_rel in report.indexes:
        index_path = (report.root / index_rel).resolve()
        try:
            body = index_path.read_text(encoding="utf-8")
        except Exception:
            continue
        for target in _iter_internal_links(body):
            target_path = _resolve_link(index_rel, target, report.root)
            target_rel = rel_by_path.get(target_path)
            if target_rel:
                incoming[target_rel] += 1

    for concept in report.concepts:
        if incoming.get(concept.rel, 0) == 0:
            report.issues.append(Issue("warning", concept.rel, "No incoming links from concepts or indexes; check discoverability."))


def generate_indexes(root: str | Path, overwrite: bool = True) -> list[Path]:
    root_path = Path(root).resolve()
    report = scan_bundle(root_path)
    by_dir: dict[Path, list[Concept]] = {}
    for concept in report.concepts:
        by_dir.setdefault(concept.path.parent, []).append(concept)

    all_dirs = {(root_path / directory).resolve() for directory in _concept_tree_dirs(report)}
    child_dirs: dict[Path, set[Path]] = {directory: set() for directory in all_dirs}
    concept_counts: dict[Path, int] = {directory: 0 for directory in all_dirs}

    for concept in report.concepts:
        concept_dir = concept.path.parent.resolve()
        for directory in all_dirs:
            try:
                concept.path.relative_to(directory)
            except ValueError:
                continue
            concept_counts[directory] = concept_counts.get(directory, 0) + 1

        current = root_path
        for part in concept.path.relative_to(root_path).parts[:-1]:
            child = (current / part).resolve()
            child_dirs.setdefault(current.resolve(), set()).add(child)
            current = child

    written: list[Path] = []
    for directory in sorted(all_dirs, key=lambda path: path.relative_to(root_path).as_posix()):
        concepts = by_dir.get(directory, [])
        index_path = directory / "index.md"
        if index_path.exists() and not overwrite:
            continue
        title = "Bundle Index" if directory == root_path else directory.name.replace("-", " ").replace("_", " ").title()
        lines = [f"# {title}", ""]

        children = sorted(child_dirs.get(directory.resolve(), set()), key=lambda path: path.name)
        if children:
            lines.extend(["## Directories", ""])
            for child in children:
                rel_link = os.path.relpath(child / "index.md", directory).replace(os.sep, "/")
                count = concept_counts.get(child.resolve(), 0)
                noun = "concept" if count == 1 else "concepts"
                display = child.name.replace("-", " ").replace("_", " ").title()
                lines.append(f"* [{display}]({rel_link}) - {count} {noun}.")
            lines.append("")

        if concepts:
            lines.extend(["## Concepts", ""])
        for concept in sorted(concepts, key=lambda c: c.rel):
            rel_link = os.path.relpath(concept.path, directory).replace(os.sep, "/")
            display = concept.frontmatter.get("title") or Path(concept.rel).stem.replace("-", " ").title()
            desc = concept.frontmatter.get("description") or "No description."
            lines.append(f"* [{display}]({rel_link}) - {desc}")
        lines.append("")
        index_path.write_text("\n".join(lines), encoding="utf-8")
        written.append(index_path)
    return written


def graph(root: str | Path) -> dict[str, Any]:
    report = scan_bundle(root)
    nodes = []
    edges = []
    rel_by_path = {c.path.resolve(): c.rel for c in report.concepts}
    for concept in report.concepts:
        nodes.append(
            {
                "id": concept.concept_id,
                "path": concept.rel,
                "type": concept.frontmatter.get("type"),
                "title": concept.frontmatter.get("title"),
                "description": concept.frontmatter.get("description"),
                "tags": concept.frontmatter.get("tags", []),
            }
        )
        for target in _iter_internal_links(concept.body):
            target_path = _resolve_link(concept.rel, target, report.root)
            target_rel = rel_by_path.get(target_path)
            if target_rel:
                edges.append({"from": concept.concept_id, "to": target_rel[:-3], "link": target})
    return {"nodes": nodes, "edges": edges, "issue_summary": report.to_dict()}


def package_bundle(root: str | Path, output: str | Path, fmt: str = "zip") -> Path:
    root_path = Path(root).resolve()
    output_path = Path(output).resolve()
    if not root_path.is_dir():
        raise ValueError(f"Bundle path is not a directory: {root_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "zip":
        with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for path in sorted(root_path.rglob("*")):
                if path.is_file() and path.resolve() != output_path:
                    zf.write(path, path.relative_to(root_path).as_posix())
    elif fmt in {"tar", "tar.gz", "tgz"}:
        mode = "w:gz" if fmt in {"tar.gz", "tgz"} else "w"
        with tarfile.open(output_path, mode) as tf:
            for path in sorted(root_path.rglob("*")):
                if path.is_file() and path.resolve() != output_path:
                    tf.add(path, arcname=path.relative_to(root_path).as_posix())
    else:
        raise ValueError(f"Unsupported package format: {fmt}")
    return output_path


def scaffold_bundle(
    root: str | Path,
    *,
    title: str,
    seed_title: str | None = None,
    overwrite: bool = False,
) -> list[Path]:
    root_path = Path(root).resolve()
    if root_path.exists() and any(root_path.iterdir()) and not overwrite:
        raise ValueError(f"Bundle path is not empty: {root_path}")

    concept_title = seed_title or title
    concept_slug = slugify_title(concept_title)
    concept_path = root_path / "concepts" / f"{concept_slug}.md"
    now = datetime.now(timezone.utc).replace(microsecond=0)
    timestamp = now.isoformat().replace("+00:00", "Z")
    date = now.date().isoformat()

    root_path.mkdir(parents=True, exist_ok=True)
    concept_path.parent.mkdir(parents=True, exist_ok=True)

    concept_text = "\n".join(
        [
            "---",
            "type: Reference",
            f"title: {concept_title}",
            f"description: Seed concept for {title}.",
            "tags: [seed]",
            f"timestamp: {timestamp}",
            "---",
            "",
            "# Summary",
            "",
            f"{concept_title} is the seed concept for this OKF bundle. Replace this summary with sourced, task-relevant facts.",
            "",
            "# Open questions",
            "",
            "* Which authoritative sources should support this concept?",
            "* Which neighboring concepts should this file link to?",
            "",
            "# Citations",
            "",
            "No external citations have been added yet.",
            "",
        ]
    )
    log_text = "\n".join(
        [
            "# Bundle Update Log",
            "",
            f"## {date}",
            f"* **Creation**: Scaffolded `{title}` with OKF Bundle Smith.",
            "",
        ]
    )

    concept_path.write_text(concept_text, encoding="utf-8")
    log_path = root_path / "log.md"
    log_path.write_text(log_text, encoding="utf-8")
    written = [concept_path, log_path]
    written.extend(generate_indexes(root_path, overwrite=True))
    return written


def add_log_entry(root: str | Path, entry: str, kind: str = "Update", date: str | None = None) -> Path:
    root_path = Path(root).resolve()
    log_path = root_path / "log.md"
    date = date or datetime.now(timezone.utc).date().isoformat()
    new_line = f"* **{kind}**: {entry}"
    if not log_path.exists():
        text = f"# Bundle Update Log\n\n## {date}\n{new_line}\n"
    else:
        text = log_path.read_text(encoding="utf-8")
        heading = f"## {date}"
        if heading in text:
            text = text.replace(heading, f"{heading}\n{new_line}", 1)
        else:
            lines = text.splitlines()
            if lines and lines[0].startswith("#"):
                lines.insert(2, f"## {date}")
                lines.insert(3, new_line)
                text = "\n".join(lines) + "\n"
            else:
                text = f"# Bundle Update Log\n\n## {date}\n{new_line}\n\n" + text
    log_path.write_text(text, encoding="utf-8")
    return log_path


def bundle_stats(report: BundleReport) -> dict[str, Any]:
    """Summarize a bundle: counts, type/tag distribution, and link health."""
    type_counts: dict[str, int] = {}
    tag_counts: dict[str, int] = {}
    edge_count = 0
    rel_by_path = {c.path.resolve(): c.rel for c in report.concepts}
    for concept in report.concepts:
        ctype = str(concept.frontmatter.get("type") or "Untyped")
        type_counts[ctype] = type_counts.get(ctype, 0) + 1
        tags = concept.frontmatter.get("tags") or []
        if isinstance(tags, list):
            for tag in tags:
                key = str(tag)
                tag_counts[key] = tag_counts.get(key, 0) + 1
        for target in _iter_internal_links(concept.body):
            if rel_by_path.get(_resolve_link(concept.rel, target, report.root)):
                edge_count += 1

    orphans = sum(1 for issue in report.warnings if "No incoming links" in issue.message)
    broken = sum(1 for issue in report.warnings if "Broken internal link" in issue.message)
    return {
        "root": str(report.root),
        "concepts": len(report.concepts),
        "indexes": len(report.indexes),
        "logs": len(report.logs),
        "internal_edges": edge_count,
        "orphan_concepts": orphans,
        "broken_links": broken,
        "errors": len(report.errors),
        "warnings": len(report.warnings),
        "types": dict(sorted(type_counts.items(), key=lambda kv: (-kv[1], kv[0]))),
        "tags": dict(sorted(tag_counts.items(), key=lambda kv: (-kv[1], kv[0]))),
    }


def stats_markdown(report: BundleReport) -> str:
    stats = bundle_stats(report)
    lines = [
        "# OKF bundle stats",
        "",
        f"Bundle: `{stats['root']}`",
        "",
        "| metric | value |",
        "|---|---:|",
        f"| Concepts | {stats['concepts']} |",
        f"| Indexes | {stats['indexes']} |",
        f"| Logs | {stats['logs']} |",
        f"| Internal edges | {stats['internal_edges']} |",
        f"| Orphan concepts | {stats['orphan_concepts']} |",
        f"| Broken links | {stats['broken_links']} |",
        f"| Errors | {stats['errors']} |",
        f"| Warnings | {stats['warnings']} |",
        "",
    ]
    if stats["types"]:
        lines.extend(["## Concept types", "", "| type | count |", "|---|---:|"])
        lines.extend(f"| {name} | {count} |" for name, count in stats["types"].items())
        lines.append("")
    if stats["tags"]:
        top_tags = list(stats["tags"].items())[:15]
        lines.extend(["## Top tags", "", "| tag | count |", "|---|---:|"])
        lines.extend(f"| {name} | {count} |" for name, count in top_tags)
        lines.append("")
    return "\n".join(lines)


VISUALIZER_CYTOSCAPE_URL = "https://cdn.jsdelivr.net/npm/cytoscape@3.30.2/dist/cytoscape.min.js"
VISUALIZER_MARKED_URL = "https://cdn.jsdelivr.net/npm/marked@12.0.2/marked.min.js"

_TYPE_PALETTE = [
    "#2F6F5E", "#C2683B", "#3B6FC2", "#8E5BB5", "#B5495B",
    "#4C9A5A", "#C9A227", "#5B8DB5", "#A0552B", "#6B6B6B",
]


def _visualization_data(root: str | Path) -> dict[str, Any]:
    report = scan_bundle(root)
    rel_by_path = {c.path.resolve(): c.rel for c in report.concepts}

    distinct_types = sorted({str(c.frontmatter.get("type") or "Untyped") for c in report.concepts})
    type_colors = {t: _TYPE_PALETTE[i % len(_TYPE_PALETTE)] for i, t in enumerate(distinct_types)}

    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    seen_edges: set[tuple[str, str]] = set()
    for concept in report.concepts:
        ctype = str(concept.frontmatter.get("type") or "Untyped")
        tags = concept.frontmatter.get("tags") or []
        if not isinstance(tags, list):
            tags = [str(tags)]
        nodes.append(
            {
                "id": concept.concept_id,
                "path": concept.rel,
                "label": concept.frontmatter.get("title") or Path(concept.rel).stem.replace("-", " ").title(),
                "type": ctype,
                "color": type_colors[ctype],
                "description": concept.frontmatter.get("description") or "",
                "resource": str(concept.frontmatter.get("resource") or ""),
                "tags": [str(t) for t in tags],
                "body": concept.body,
            }
        )
        for target in _iter_internal_links(concept.body):
            target_rel = rel_by_path.get(_resolve_link(concept.rel, target, report.root))
            if not target_rel:
                continue
            target_id = target_rel[:-3] if target_rel.endswith(".md") else target_rel
            edge_key = (concept.concept_id, target_id)
            if target_id == concept.concept_id or edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)
            edges.append({"source": concept.concept_id, "target": target_id})

    meta = {
        "name": report.root.name,
        "concept_count": len(report.concepts),
        "edge_count": len(edges),
        "type_colors": type_colors,
        "error_count": len(report.errors),
        "warning_count": len(report.warnings),
        "generated": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
    }
    return {"nodes": nodes, "edges": edges, "meta": meta}


def build_visualization(root: str | Path) -> str:
    """Return a self-contained HTML page that renders the bundle as a graph."""
    data = _visualization_data(root)
    data_json = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    title = data["meta"]["name"] or "OKF bundle"
    return (
        _VISUALIZER_TEMPLATE.replace("__OKF_TITLE__", _html_escape(title))
        .replace("__OKF_CYTOSCAPE_URL__", VISUALIZER_CYTOSCAPE_URL)
        .replace("__OKF_MARKED_URL__", VISUALIZER_MARKED_URL)
        .replace("__OKF_DATA__", data_json)
    )


def write_visualization(root: str | Path, output: str | Path) -> Path:
    output_path = Path(output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_visualization(root), encoding="utf-8")
    return output_path


def _html_escape(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


_VISUALIZER_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>__OKF_TITLE__ - OKF bundle</title>
<script src="__OKF_CYTOSCAPE_URL__"></script>
<script src="__OKF_MARKED_URL__"></script>
<style>
  :root { --brand: #2F6F5E; --bg: #0f1417; --panel: #161d21; --ink: #e7edea; --muted: #9bb0a8; --line: #283437; }
  * { box-sizing: border-box; }
  html, body { margin: 0; height: 100%; font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; background: var(--bg); color: var(--ink); }
  #app { display: grid; grid-template-rows: auto 1fr; height: 100%; }
  header { padding: 10px 16px; border-bottom: 1px solid var(--line); display: flex; gap: 16px; align-items: center; flex-wrap: wrap; }
  header h1 { font-size: 15px; margin: 0; font-weight: 600; }
  header h1 .brand { color: var(--brand); }
  header .meta { color: var(--muted); font-size: 12px; }
  header .controls { margin-left: auto; display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
  input, select, button { background: var(--panel); color: var(--ink); border: 1px solid var(--line); border-radius: 6px; padding: 6px 10px; font-size: 13px; }
  button { cursor: pointer; }
  button:hover { border-color: var(--brand); }
  #main { display: grid; grid-template-columns: 1fr 380px; min-height: 0; }
  #cy { width: 100%; height: 100%; background: radial-gradient(circle at 30% 20%, #14201d, var(--bg)); }
  #side { border-left: 1px solid var(--line); background: var(--panel); overflow: auto; padding: 16px; }
  #side .empty { color: var(--muted); font-size: 13px; line-height: 1.6; }
  #side h2 { font-size: 17px; margin: 0 0 4px; }
  .pill { display: inline-block; font-size: 11px; padding: 2px 8px; border-radius: 999px; background: #22302c; color: var(--muted); margin: 2px 4px 2px 0; }
  .pill.type { color: #fff; }
  .desc { color: var(--muted); font-size: 13px; margin: 8px 0 12px; }
  .links { margin: 12px 0; }
  .links h3 { font-size: 12px; text-transform: uppercase; letter-spacing: .04em; color: var(--muted); margin: 12px 0 6px; }
  .links a, .body a { color: #7fd1b9; cursor: pointer; text-decoration: none; }
  .links a:hover, .body a:hover { text-decoration: underline; }
  .links ul { margin: 0; padding-left: 18px; }
  .body { border-top: 1px solid var(--line); margin-top: 14px; padding-top: 12px; font-size: 13.5px; line-height: 1.6; }
  .body h1, .body h2, .body h3 { line-height: 1.3; }
  .body table { border-collapse: collapse; width: 100%; font-size: 12.5px; }
  .body th, .body td { border: 1px solid var(--line); padding: 4px 8px; text-align: left; }
  .body code { background: #0d1316; padding: 1px 5px; border-radius: 4px; }
  .body pre { background: #0d1316; padding: 10px; border-radius: 8px; overflow: auto; }
  .legend { display: flex; gap: 6px; flex-wrap: wrap; }
  .legend .item { display: flex; gap: 5px; align-items: center; font-size: 12px; color: var(--muted); cursor: pointer; user-select: none; padding: 2px 6px; border-radius: 6px; }
  .legend .item.off { opacity: .35; }
  .legend .dot { width: 10px; height: 10px; border-radius: 50%; }
  #banner { display: none; padding: 8px 16px; background: #4a2f2f; color: #ffd9d9; font-size: 13px; }
  .resource { font-size: 12px; word-break: break-all; }
</style>
</head>
<body>
<div id="app">
  <header>
    <h1><span class="brand">OKF</span> &middot; __OKF_TITLE__</h1>
    <span class="meta" id="metaText"></span>
    <div class="controls">
      <input id="search" type="search" placeholder="Search concepts..." autocomplete="off" />
      <select id="layout" title="Layout">
        <option value="cose">Force</option>
        <option value="concentric">Concentric</option>
        <option value="breadthfirst">Hierarchy</option>
        <option value="circle">Circle</option>
        <option value="grid">Grid</option>
      </select>
      <button id="fit">Fit</button>
    </div>
  </header>
  <div id="banner"></div>
  <div id="main">
    <div id="cy"></div>
    <aside id="side">
      <div class="legend" id="legend"></div>
      <div id="detail"><p class="empty">Click a node to inspect a concept. Use search to filter, the legend to toggle types, and links in the panel to traverse the graph.</p></div>
    </aside>
  </div>
</div>
<script>
"use strict";
const DATA = __OKF_DATA__;
const byId = new Map(DATA.nodes.map(n => [n.id, n]));
const hiddenTypes = new Set();

document.getElementById("metaText").textContent =
  DATA.meta.concept_count + " concepts · " + DATA.meta.edge_count + " links · " +
  DATA.meta.error_count + " errors · " + DATA.meta.warning_count + " warnings";

if (typeof cytoscape === "undefined") {
  const b = document.getElementById("banner");
  b.style.display = "block";
  b.textContent = "Could not load the Cytoscape library from the CDN. This viewer needs internet access to render the graph.";
}

function normalizePath(base, rel) {
  const baseDir = base.includes("/") ? base.slice(0, base.lastIndexOf("/")) : "";
  const parts = (baseDir ? baseDir.split("/") : []);
  for (const seg of rel.split("/")) {
    if (seg === "" || seg === ".") continue;
    if (seg === "..") parts.pop();
    else parts.push(seg);
  }
  return parts.join("/");
}

function hrefToId(href, currentPath) {
  let h = href.split("#")[0].split("?")[0];
  if (!h.endsWith(".md")) return null;
  let rel;
  if (h.startsWith("/")) rel = h.slice(1);
  else rel = normalizePath(currentPath, h);
  return rel.replace(/\.md$/, "");
}

const cy = (typeof cytoscape !== "undefined") ? cytoscape({
  container: document.getElementById("cy"),
  elements: [
    ...DATA.nodes.map(n => ({ data: { id: n.id, label: n.label, color: n.color, type: n.type } })),
    ...DATA.edges.map(e => ({ data: { id: e.source + "->" + e.target, source: e.source, target: e.target } })),
  ],
  style: [
    { selector: "node", style: {
      "background-color": "data(color)", "label": "data(label)", "color": "#dfeae6",
      "font-size": 9, "text-wrap": "wrap", "text-max-width": 120, "text-valign": "bottom",
      "text-margin-y": 4, "width": 18, "height": 18, "border-width": 1, "border-color": "#0c1113" } },
    { selector: "edge", style: {
      "width": 1, "line-color": "#3a4b47", "target-arrow-color": "#3a4b47",
      "target-arrow-shape": "triangle", "arrow-scale": 0.8, "curve-style": "bezier", "opacity": 0.7 } },
    { selector: "node.selected", style: { "border-width": 3, "border-color": "#7fd1b9", "width": 26, "height": 26 } },
    { selector: ".dim", style: { "opacity": 0.12 } },
    { selector: ".hl", style: { "opacity": 1 } },
    { selector: ".hidden", style: { "display": "none" } },
  ],
  layout: { name: "cose", animate: false, padding: 40 },
  wheelSensitivity: 0.25,
}) : null;

function runLayout(name) {
  if (!cy) return;
  const opts = { name, animate: false, padding: 40 };
  if (name === "concentric") { opts.concentric = n => n.degree(); opts.levelWidth = () => 4; }
  cy.layout(opts).run();
}

function renderDetail(node) {
  const n = byId.get(node.id());
  if (!n) return;
  const out = DATA.edges.filter(e => e.source === n.id).map(e => e.target);
  const back = DATA.edges.filter(e => e.target === n.id).map(e => e.source);
  const tagPills = n.tags.map(t => '<span class="pill">' + escapeHtml(t) + "</span>").join("");
  const linkList = (ids) => ids.length
    ? "<ul>" + ids.map(id => '<li><a data-goto="' + escapeHtml(id) + '">' + escapeHtml((byId.get(id) || {}).label || id) + "</a></li>").join("") + "</ul>"
    : '<p class="empty">None.</p>';
  const safeResource = safeExternalHref(n.resource);
  const resource = n.resource
    ? '<p class="resource">Resource: ' + (safeResource
      ? '<a href="' + escapeHtml(safeResource) + '" target="_blank" rel="noopener noreferrer">' + escapeHtml(n.resource) + "</a>"
      : escapeHtml(n.resource)) + "</p>"
    : "";
  const bodyHtml = (typeof marked !== "undefined")
    ? sanitizeHtml(marked.parse(n.body || ""))
    : "<pre>" + escapeHtml(n.body || "") + "</pre>";
  document.getElementById("detail").innerHTML =
    '<h2>' + escapeHtml(n.label) + "</h2>" +
    '<span class="pill type" style="background:' + n.color + '">' + escapeHtml(n.type) + "</span>" + tagPills +
    '<p class="desc">' + escapeHtml(n.description) + "</p>" + resource +
    '<div class="links"><h3>Outgoing (' + out.length + ")</h3>" + linkList(out) +
    "<h3>Backlinks (" + back.length + ")</h3>" + linkList(back) + "</div>" +
    '<div class="body">' + bodyHtml + "</div>";

  document.querySelectorAll("#detail [data-goto]").forEach(a =>
    a.addEventListener("click", () => selectNode(a.getAttribute("data-goto"))));
  document.querySelectorAll("#detail .body a[href]").forEach(a => {
    const id = hrefToId(a.getAttribute("href") || "", n.path);
    if (id && byId.has(id)) a.addEventListener("click", ev => { ev.preventDefault(); selectNode(id); });
  });
}

function selectNode(id) {
  if (!cy) { const n = byId.get(id); if (n) renderDetail({ id: () => id }); return; }
  const ele = cy.getElementById(id);
  if (!ele || ele.empty()) return;
  cy.nodes().removeClass("selected");
  ele.addClass("selected");
  cy.animate({ center: { eles: ele }, zoom: Math.max(cy.zoom(), 1.2) }, { duration: 250 });
  renderDetail(ele);
}

function escapeHtml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function hasScheme(value) {
  return /^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(String(value || "").trim());
}

function isSafeUrl(value) {
  const raw = String(value || "").trim();
  if (!raw || raw.startsWith("#")) return true;
  if (!hasScheme(raw)) return true;
  try {
    const parsed = new URL(raw);
    return parsed.protocol === "http:" || parsed.protocol === "https:" || parsed.protocol === "mailto:";
  } catch {
    return false;
  }
}

function safeExternalHref(value) {
  const raw = String(value || "").trim();
  if (!raw || !hasScheme(raw)) return "";
  try {
    const parsed = new URL(raw);
    return (parsed.protocol === "http:" || parsed.protocol === "https:" || parsed.protocol === "mailto:") ? raw : "";
  } catch {
    return "";
  }
}

function sanitizeHtml(html) {
  const template = document.createElement("template");
  template.innerHTML = String(html || "");
  const blocked = new Set(["SCRIPT", "STYLE", "IFRAME", "OBJECT", "EMBED", "LINK", "META", "BASE", "FORM", "INPUT", "BUTTON", "TEXTAREA", "SELECT", "SVG", "MATH"]);
  template.content.querySelectorAll("*").forEach(el => {
    if (blocked.has(el.tagName)) {
      el.remove();
      return;
    }
    [...el.attributes].forEach(attr => {
      const name = attr.name.toLowerCase();
      const value = attr.value || "";
      if (name.startsWith("on") || name === "style" || name === "srcdoc") {
        el.removeAttribute(attr.name);
        return;
      }
      if (["href", "src", "xlink:href", "action", "formaction"].includes(name) && !isSafeUrl(value)) {
        el.removeAttribute(attr.name);
      }
    });
    if (el.tagName === "A") {
      el.setAttribute("rel", "noopener noreferrer");
    }
  });
  return template.innerHTML;
}

function applyFilters() {
  if (!cy) return;
  const q = document.getElementById("search").value.trim().toLowerCase();
  cy.batch(() => {
    cy.nodes().forEach(node => {
      const n = byId.get(node.id());
      const typeHidden = hiddenTypes.has(n.type);
      const matches = !q || (n.label + " " + n.type + " " + n.description + " " + n.tags.join(" ")).toLowerCase().includes(q);
      node.toggleClass("hidden", typeHidden);
      node.toggleClass("dim", !typeHidden && !matches);
      node.toggleClass("hl", !typeHidden && !!q && matches);
    });
    cy.edges().forEach(edge => {
      edge.toggleClass("hidden", edge.source().hasClass("hidden") || edge.target().hasClass("hidden"));
      edge.toggleClass("dim", !!q && (edge.source().hasClass("dim") || edge.target().hasClass("dim")));
    });
  });
}

function buildLegend() {
  const legend = document.getElementById("legend");
  const entries = Object.entries(DATA.meta.type_colors);
  legend.innerHTML = entries.map(([type, color]) =>
    '<span class="item" data-type="' + escapeHtml(type) + '"><span class="dot" style="background:' + color + '"></span>' + escapeHtml(type) + "</span>").join("");
  legend.querySelectorAll(".item").forEach(item => item.addEventListener("click", () => {
    const type = item.getAttribute("data-type");
    if (hiddenTypes.has(type)) hiddenTypes.delete(type); else hiddenTypes.add(type);
    item.classList.toggle("off");
    applyFilters();
  }));
}

buildLegend();
if (cy) {
  cy.on("tap", "node", evt => selectNode(evt.target.id()));
  document.getElementById("search").addEventListener("input", applyFilters);
  document.getElementById("layout").addEventListener("change", e => runLayout(e.target.value));
  document.getElementById("fit").addEventListener("click", () => cy.fit(undefined, 40));
}
</script>
</body>
</html>
"""


def markdown_report(report: BundleReport) -> str:
    lines = [
        f"# OKF validation report",
        "",
        f"Bundle: `{report.root}`",
        f"Concepts: **{len(report.concepts)}**",
        f"Indexes: **{len(report.indexes)}**",
        f"Logs: **{len(report.logs)}**",
        f"Errors: **{len(report.errors)}**",
        f"Warnings: **{len(report.warnings)}**",
        "",
    ]
    if not report.issues:
        lines.append("No issues found.")
        return "\n".join(lines)
    lines.append("## Issues")
    lines.append("")
    for issue in report.issues:
        marker = "ERROR" if issue.severity == "error" else "WARN" if issue.severity == "warning" else "INFO"
        lines.append(f"* **{marker}** `{issue.path}` - {issue.message}")
    return "\n".join(lines)
